sudo: required
services:
  - docker

before_install:
  - docker build -t abhibee/docker-react -f Dockerfile.dev .

script:
  - docker run abhibee/docker-react npm run test -- --coverage

deploy:
  - provider: elasticbeanstalk
  - region: "us-east-2"
  - app: "docker-react"
  - env: "DockerReact-env"
  - bucket-name: "elasticbeanstalk-us-east-2-681762438553"
  - bucket-path: "docker-react"
  on:
    branch: master
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: 
    secure: "$SECRET_ACCESS_KEY"
